language: ruby

rvm:
- 2.6.3

branches:
  only:
  - master

install:
- gem install bundler

script:
- gem build foreman_gridscale.gemspec 

deploy:
  provider: rubygems
  api_key: $RUBYGEMS_APIKEY
  gem: foreman_gridscale
  gemspec: foreman_gridscale.gemspec
